/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentCreateNestedManyWithoutTasksInput } from "./CommentCreateNestedManyWithoutTasksInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { HistoryCreateNestedManyWithoutTasksInput } from "./HistoryCreateNestedManyWithoutTasksInput";
import { LabelCreateNestedManyWithoutTasksInput } from "./LabelCreateNestedManyWithoutTasksInput";
import { EnumTaskPriority } from "./EnumTaskPriority";
import { ProjectWhereUniqueInput } from "../../project/base/ProjectWhereUniqueInput";
import { EnumTaskStatus } from "./EnumTaskStatus";
import { StepsCreateNestedManyWithoutTasksInput } from "./StepsCreateNestedManyWithoutTasksInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class TaskCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutTasksInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutTasksInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutTasksInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutTasksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dueDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => HistoryCreateNestedManyWithoutTasksInput,
  })
  @ValidateNested()
  @Type(() => HistoryCreateNestedManyWithoutTasksInput)
  @IsOptional()
  @Field(() => HistoryCreateNestedManyWithoutTasksInput, {
    nullable: true,
  })
  histories?: HistoryCreateNestedManyWithoutTasksInput;

  @ApiProperty({
    required: false,
    type: () => LabelCreateNestedManyWithoutTasksInput,
  })
  @ValidateNested()
  @Type(() => LabelCreateNestedManyWithoutTasksInput)
  @IsOptional()
  @Field(() => LabelCreateNestedManyWithoutTasksInput, {
    nullable: true,
  })
  labels?: LabelCreateNestedManyWithoutTasksInput;

  @ApiProperty({
    required: false,
    enum: EnumTaskPriority,
  })
  @IsEnum(EnumTaskPriority)
  @IsOptional()
  @Field(() => EnumTaskPriority, {
    nullable: true,
  })
  priority?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => ProjectWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProjectWhereUniqueInput)
  @IsOptional()
  @Field(() => ProjectWhereUniqueInput, {
    nullable: true,
  })
  project?: ProjectWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumTaskStatus,
  })
  @IsEnum(EnumTaskStatus)
  @IsOptional()
  @Field(() => EnumTaskStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => StepsCreateNestedManyWithoutTasksInput,
  })
  @ValidateNested()
  @Type(() => StepsCreateNestedManyWithoutTasksInput)
  @IsOptional()
  @Field(() => StepsCreateNestedManyWithoutTasksInput, {
    nullable: true,
  })
  stepsItems?: StepsCreateNestedManyWithoutTasksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { TaskCreateInput as TaskCreateInput };
