/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentUpdateManyWithoutTasksInput } from "./CommentUpdateManyWithoutTasksInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { HistoryUpdateManyWithoutTasksInput } from "./HistoryUpdateManyWithoutTasksInput";
import { LabelUpdateManyWithoutTasksInput } from "./LabelUpdateManyWithoutTasksInput";
import { EnumTaskPriority } from "./EnumTaskPriority";
import { ProjectWhereUniqueInput } from "../../project/base/ProjectWhereUniqueInput";
import { EnumTaskStatus } from "./EnumTaskStatus";
import { StepsUpdateManyWithoutTasksInput } from "./StepsUpdateManyWithoutTasksInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class TaskUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutTasksInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutTasksInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutTasksInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutTasksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dueDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => HistoryUpdateManyWithoutTasksInput,
  })
  @ValidateNested()
  @Type(() => HistoryUpdateManyWithoutTasksInput)
  @IsOptional()
  @Field(() => HistoryUpdateManyWithoutTasksInput, {
    nullable: true,
  })
  histories?: HistoryUpdateManyWithoutTasksInput;

  @ApiProperty({
    required: false,
    type: () => LabelUpdateManyWithoutTasksInput,
  })
  @ValidateNested()
  @Type(() => LabelUpdateManyWithoutTasksInput)
  @IsOptional()
  @Field(() => LabelUpdateManyWithoutTasksInput, {
    nullable: true,
  })
  labels?: LabelUpdateManyWithoutTasksInput;

  @ApiProperty({
    required: false,
    enum: EnumTaskPriority,
  })
  @IsEnum(EnumTaskPriority)
  @IsOptional()
  @Field(() => EnumTaskPriority, {
    nullable: true,
  })
  priority?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => ProjectWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProjectWhereUniqueInput)
  @IsOptional()
  @Field(() => ProjectWhereUniqueInput, {
    nullable: true,
  })
  project?: ProjectWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumTaskStatus,
  })
  @IsEnum(EnumTaskStatus)
  @IsOptional()
  @Field(() => EnumTaskStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => StepsUpdateManyWithoutTasksInput,
  })
  @ValidateNested()
  @Type(() => StepsUpdateManyWithoutTasksInput)
  @IsOptional()
  @Field(() => StepsUpdateManyWithoutTasksInput, {
    nullable: true,
  })
  stepsItems?: StepsUpdateManyWithoutTasksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { TaskUpdateInput as TaskUpdateInput };
